name: SlapChop CI
on: [push, pull_request]
jobs:
  deploy:
    name: "Deploy to Rhya"
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.STAGING_SSH_USER }}
          SSH_KEY: ${{ secrets.PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.STAGING_SSH_HOST }}

      - name: Stop any screens
        run: ssh staging "screen -ls | grep '(Detached)' | awk 'sys {screen -S $1 -X quit}'"

      - name: Check out the source
        run: ssh staging 'cd ~/git/slapchop ; git pull'

      - name: Start the server in a fresh screen
        if: ${{ always() }}
        run: ssh staging 'screen -dmS slapchop ~/git/slapchop/run_slapchop.bat'
